CREATE TABLE IF NOT EXISTS "michiganHandOutcomeResponse" (
	"id" serial PRIMARY KEY NOT NULL,
	"date" date DEFAULT now(),
	"patientId" integer,
	"q1" integer,
	"q2" integer,
	"q3" integer,
	"q4" integer,
	"q5" integer,
	"q6" integer,
	"q7" integer,
	"q8" integer,
	"q9" integer,
	"q10" integer,
	"q11" integer,
	"q12" integer,
	"q13" integer,
	"q14" integer,
	"q15" integer,
	"q16" integer,
	"q17" integer,
	"q18" integer,
	"q19" integer,
	"q20" integer,
	"q21" integer,
	"q22" integer,
	"q23" integer,
	"q24" integer,
	"q25" integer,
	"q26" integer,
	"q27" integer,
	"q28" integer,
	"q29" integer,
	"q30" integer,
	"q31" integer,
	"q32" integer,
	"q33" integer,
	"q34" integer,
	"q35" integer,
	"q36" integer,
	"q37" integer,
	"q38" integer,
	"q39" integer,
	"q40" integer,
	"q41" integer,
	"q42" integer,
	"q43" integer,
	"q44" integer,
	"q45" integer,
	"q46" integer,
	"q47" integer,
	"q48" integer,
	"q49" integer,
	"q50" integer,
	"q51" integer,
	"q52" integer,
	"q53" integer,
	"q54" integer,
	"q55" integer,
	"q56" integer,
	"q57" integer
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "michiganHandOutcomeResponse" ADD CONSTRAINT "michiganHandOutcomeResponse_patientId_patient_id_fk" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
