ALTER TABLE "bctResponse" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "bsrsResponse" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q31" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q32" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q33" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q34" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q35" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q36" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q37" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "q38" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "hasJob" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "job" text;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "hasSportOrInstrument" integer;--> statement-breakpoint
ALTER TABLE "dashResponse" ADD COLUMN "sportOrInstrument" text;--> statement-breakpoint
ALTER TABLE "michiganHandOutcomeResponse" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q1" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q2" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q3" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q4" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q5" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q6" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q7" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q8" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q9" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q10" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q11" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q12" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q13" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q14" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q15" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q16" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q17" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q18" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "q19" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "hasJob" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "job" text;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "hasSportOrInstrument" integer;--> statement-breakpoint
ALTER TABLE "qDashResponse" ADD COLUMN "sportOrInstrument" text;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q1" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q2" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q3" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q4" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q5" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q6" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q7" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q8" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q9" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q10" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q11" integer;--> statement-breakpoint
ALTER TABLE "sf12Response" ADD COLUMN "q12" integer;--> statement-breakpoint
ALTER TABLE "sf36Response" ADD COLUMN "done" boolean;--> statement-breakpoint
ALTER TABLE "whoqolBrefResponse" ADD COLUMN "done" boolean;