CREATE TABLE IF NOT EXISTS "admins" (
	"username" text PRIMARY KEY NOT NULL,
	"pwd" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "raynaudData" (
	"id" serial PRIMARY KEY NOT NULL,
	"patientId" integer NOT NULL,
	"postOPYear" integer,
	"affectedSide" integer,
	"comorbidities" integer,
	"psychologicalDisorder" integer,
	"smoking" integer,
	"autoimmuneDzSince" text,
	"raynaudSince" text,
	"surgeryDate" text,
	"timeFromAutoimmneToOp" integer,
	"yearsFromRaynaudToOp" integer,
	"pastIntervention" integer,
	"oralVasodilatorTreatment" integer,
	"seasonal" integer,
	"discoloration" integer,
	"numbness" integer,
	"pain" integer,
	"digitalUlcerationPresence" integer,
	"digitalUlcerationNumbers" integer,
	"attackFrequency" integer,
	"nailfoldCapillaryMicroscopy" integer,
	"nerveOfHenleDistanceToPisiform" numeric,
	"icgIngressBGPreOp" numeric,
	"icgIngressBGPostOp" numeric,
	"icgIngressRateBGPreOp" numeric,
	"icgIngressRateBGPostOp" numeric,
	"icgIngressImprovementBG" numeric,
	"icgIngressRateImprovementBG" numeric,
	"icgEgressBGPreOp" numeric,
	"icgEgressBGPostOp" numeric,
	"icgEgressRateBGPreOp" numeric,
	"icgEgressRateBGPostOp" numeric,
	"icgEgressImprovementBG" numeric,
	"icgEgressRateImprovementBG" numeric,
	"icgIngressBrightestAreaPreOp" numeric,
	"icgIngressBrightestAreaPostOp" numeric,
	"icgIngressRateBrightestAreaPreOp" numeric,
	"icgIngressRateBrightestAreaPostOp" numeric,
	"icgIngressImprovementBrightestArea" numeric,
	"icgIngressRateImprovementBrightestArea" numeric,
	"icgEgressBrightestAreaPreOp" numeric,
	"icgEgressBrightestAreaPostOp" numeric,
	"icgEgressRateBrightestAreaPreOp" numeric,
	"icgEgressRateBrightestAreaPostOp" numeric,
	"icgEgressImprovementBrightestArea" numeric,
	"icgEgressRateImprovementBrightestArea" numeric,
	"finger2ICGIngressPreOp" numeric,
	"finger2ICGIngressPostOp" numeric,
	"finger2ICGIngressRatePreOp" numeric,
	"finger2ICGIngressRatePostOp" numeric,
	"finger2ICGIngressImprovement" numeric,
	"finger2ICGIngressRateImprovement" numeric,
	"finger2ICGEgressPreOp" numeric,
	"finger2ICGEgressPostOp" numeric,
	"finger2ICGEgressRatePreOp" numeric,
	"finger2ICGEgressRatePostOp" numeric,
	"finger2ICGEgressImprovement" numeric,
	"finger2ICGEgressRateImprovement" numeric,
	"finger3ICGIngressPreOp" numeric,
	"finger3ICGIngressPostOp" numeric,
	"finger3ICGIngressRatePreOp" numeric,
	"finger3ICGIngressRatePostOp" numeric,
	"finger3ICGIngressImprovement" numeric,
	"finger3ICGIngressRateImprovement" numeric,
	"finger3ICGEgressPreOp" numeric,
	"finger3ICGEgressPostOp" numeric,
	"finger3ICGEgressRatePreOp" numeric,
	"finger3ICGEgressRatePostOp" numeric,
	"finger3ICGEgressImprovement" numeric,
	"finger3ICGEgressRateImprovement" numeric,
	"finger4ICGIngressPreOp" numeric,
	"finger4ICGIngressPostOp" numeric,
	"finger4ICGIngressRatePreOp" numeric,
	"finger4ICGIngressRatePostOp" numeric,
	"finger4ICGIngressImprovement" numeric,
	"finger4ICGIngressRateImprovement" numeric,
	"finger4ICGEgressPreOp" numeric,
	"finger4ICGEgressPostOp" numeric,
	"finger4ICGEgressRatePreOp" numeric,
	"finger4ICGEgressRatePostOp" numeric,
	"finger4ICGEgressImprovement" numeric,
	"finger4ICGEgressRateImprovement" numeric,
	"digitalSkinTemperature" numeric,
	"digitalSkinBloodFlow" numeric,
	"MHOOverallR" numeric,
	"MHOOverallL" numeric,
	"MHOActivitiesROH" numeric,
	"MHOActivitiesROverall" numeric,
	"MHOActivitiesLOH" numeric,
	"MHOActivitiesLOverall" numeric,
	"MHOActivitiesTH" numeric,
	"MHOWork" numeric,
	"MHOPain" numeric,
	"MHOAestheticsR" numeric,
	"MHOAestheticsL" numeric,
	"MHOSatisfactionR" numeric,
	"MHOSatisfactionL" numeric,
	"SF36PhyFunc" numeric,
	"SF36RolePhy" numeric,
	"SF36BodyPain" numeric,
	"SF36GenHealth" numeric,
	"SF36Vitality" numeric,
	"SF36SocialFunc" numeric,
	"SF36RoleEmotion" numeric,
	"SF36MentalHealth" numeric
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "raynaudData" ADD CONSTRAINT "raynaudData_patientId_patient_id_fk" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
